// --- DATA MOCK ---
export const MOCK_PRODUCTS = [
  {
    id: 1,
    name: "Amerta",
    category: "Distilled Beverages",
    price: 48000,
    abv: "40%",
    volume: "750ml",
    description: "Distilasi murni dari beras Bali dan nira kelapa, diperam dalam tong kayu jati lokal. Halus, kompleks, dan berakar kuat dalam sejarah nusantara.",
    imageUrl: "./tokcer/amerta.png",
    rating: 4.8,
  },
  {
    id: 2,
    name: "Baby Berry",
    category: "Distilled Beverages",
    price: 50000,
    abv: "15%",
    volume: "500ml",
    description: "Anggur beras manis tradisional Bali, berwarna keemasan dan difermentasi secara alami. Aroma madu, karamel, dan beras ketan manis. Sempurna sebagai hidangan penutup.",
    imageUrl: "./tokcer/baby_berry.png",
    rating: 4.5,
  },
  {
    id: 3,
    name: "Ananas",
    category: "Distilled Beverages",
    price: 50000,
    abv: "45%",
    volume: "700ml",
    description: "Spirit jernih dan kuat yang disuling tangan dari nira palma liar di Nusa Tenggara Timur. Berani, bersahaja, dan secara tradisional diminum langsung.",
    imageUrl: "./tokcer/ananas.png",
    rating: 4.9,
  },
  {
    id: 4,
    name: "Intisari",
    category: "Herbal Drink",
    price: 55000,
    abv: "19%",
    volume: "620ml",
    description: "Anggur herbal fermentasi tradisional, dikenal dengan rasa manis dan aroma jamu. Klasik abadi yang populer di berbagai generasi.",
    imageUrl: "./tokcer/intisari.png",
    rating: 4.2,
  },
  {
    id: 5,
    name: "Api",
    category: "Herbal Drink",
    price: 80000,
    abv: "48%",
    volume: "700ml",
    description: "Arrack berkadar alkohol tinggi dari tetes tebu Jawa, sempurna untuk koktail klasik seperti Swedish Punsch.",
    imageUrl: "./tokcer/api.png",
    rating: 4.7,
  },
  {
    id: 6,
    name: "Anggur Merah Gold",
    category: "Herbal Drink",
    price: 70000,
    abv: "48%",
    volume: "700ml",
    description: "Arrack berkadar alkohol tinggi dari tetes tebu Jawa, sempurna untuk koktail klasik seperti Swedish Punsch.",
    imageUrl: "./tokcer/anggur_merah_gold.png",
    rating: 4.7,
  },
  {
    id: 7,
    name: "Anggur Merah",
    category: "Herbal Drink",
    price: 65000,
    abv: "48%",
    volume: "700ml",
    description: "Arrack berkadar alkohol tinggi dari tetes tebu Jawa, sempurna untuk koktail klasik seperti Swedish Punsch.",
    imageUrl: "./tokcer/anggur_merah.png",
    rating: 4.7,
  },
  {
    id: 8,
    name: "Intisari Ijo",
    category: "Herbal Drink",
    price: 65000,
    abv: "48%",
    volume: "700ml",
    description: "Arrack berkadar alkohol tinggi dari tetes tebu Jawa, sempurna untuk koktail klasik seperti Swedish Punsch.",
    imageUrl: "./tokcer/intisari_ijo.png",
    rating: 4.7,
  },
  {
    id: 9,
    name: "Intisari Ijo",
    category: "Herbal Drink",
    price: 65000,
    abv: "48%",
    volume: "700ml",
    description: "Arrack berkadar alkohol tinggi dari tetes tebu Jawa, sempurna untuk koktail klasik seperti Swedish Punsch.",
    imageUrl: "./tokcer/intisari_ijo.png",
    rating: 4.7,
  },
  {
    id: 10,
    name: "Intisari Blackcurant",
    category: "Herbal Drink",
    price: 65000,
    abv: "48%",
    volume: "700ml",
    description: "Arrack berkadar alkohol tinggi dari tetes tebu Jawa, sempurna untuk koktail klasik seperti Swedish Punsch.",
    imageUrl: "./tokcer/intisari_blackcurant.png",
    rating: 4.7,
  },
  {
    id: 11,
    name: "Smirnoff Ice",
    category: "Vodka",
    price: 35000,
    abv: "48%",
    volume: "700ml",
    description: "Arrack berkadar alkohol tinggi dari tetes tebu Jawa, sempurna untuk koktail klasik seperti Swedish Punsch.",
    imageUrl: "./tokcer/smirnoff_ice.png",
    rating: 4.7,
  },
  {
    id: 12,
    name: "Smirnoff Vodka",
    category: "Vodka",
    price: 35000,
    abv: "48%",
    volume: "700ml",
    description: "Arrack berkadar alkohol tinggi dari tetes tebu Jawa, sempurna untuk koktail klasik seperti Swedish Punsch.",
    imageUrl: "./tokcer/smirnoff_vodka.png",
    rating: 4.7,
  },
  {
    id: 13,
    name: "Smirnoff Ice Pink",
    category: "Vodka",
    price: 35000,
    abv: "48%",
    volume: "700ml",
    description: "Arrack berkadar alkohol tinggi dari tetes tebu Jawa, sempurna untuk koktail klasik seperti Swedish Punsch.",
    imageUrl: "./tokcer/smirnoff_ice_pink.png",
    rating: 4.7,
  },
];

export const CATEGORIES = ["Semua", "Distilled Beverages", "Herbal Drink", "Vodka"];

export const PRIMARY_COLOR_ACCENT = '#AA8844';
export const ACCENT_COLOR_CLASS = 'text-[#AA8844]';
export const DARK_BG = 'bg-[#121212]';
export const TEXT_LIGHT = 'text-gray-200';
export const TEXT_MUTED = 'text-gray-400';
export const LOGO_URL = "./logo/logo.png";